name = "lapce-css"
version = "0.0.1"
author = "eloilson"
display-name = "Css"
description = "Adds CSS and SCSS support"
repository = "https://github.com/elo1lson/lapce-css"
wasm = "bin/lapce-css.wasm"
icon = "css.svg"

[activation]
language = ["css","scss"]
workspace-contains = ["*/*.css", "*/*.scss"]

[config."volt.serverPath"]
default = ""
description = "Path to css-language-server"

[config."volt.serverArgs"]
default = ["--stdio"]
description = "LSP server arguments to pass when launching"

# [config."lspSettingArray"]
# default = []
# description = ""

# [config."lspSettingString"]
# default = ""
# description = ""

# [config."lspSettingBool"]
# default = false
# description = ""
