name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm32-wasi target
      run: rustup target add wasm32-wasi
    - name: Install cargo-make
      run: cargo install cargo-make
    - name: Run cargo make dev
      run: cargo make dev --verbose
